import { FormEvent, useEffect, useMemo, useState } from 'react'
import { request, signIn } from './api'
import { AIStatusCard, Agenda3, Care3, Home3, Journal3 } from './Sprint3'

type User = { id: number; name: string; email: string; role: string }
type Page = 'home' | 'checkin' | 'journal' | 'care' | 'chat' | 'help' | 'agenda' | 'privacy' | 'dashboard' | 'research' | 'admin'
const labels: Record<Page, [string, string, string]> = {
  home: ['⌂', 'Início', 'Sua jornada de cuidado complementar'], checkin: ['◉', 'Check-in', 'Perceba padrões sem transformar humor em diagnóstico'], journal: ['✎', 'Diário', 'Espaço privado, pessoal e isolado'], care: ['♡', 'Autocuidado', 'Práticas curtas, revisadas e versionadas'], chat: ['◌', 'Assistente IA', 'Conversa educativa com fontes e limites'], help: ['⚑', 'Safety Center', 'Ajuda humana e próximos passos seguros'], agenda: ['▣', 'Agenda', 'Conexão com profissionais da demonstração'], privacy: ['⚿', 'Privacidade', 'Controle e histórico de consentimento'], dashboard: ['▦', 'Dashboard', 'Indicadores operacionais somente agregados'], research: ['◇', 'Research Lab', 'Experimento de engajamento não clínico'], admin: ['⚙', 'Admin', 'Conhecimento publicado e governança'],
}

function useLoad(path: string, token: string, refreshKey: unknown = '') {
  const [data, setData] = useState<any>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const reload = () => { setLoading(true); setError(''); return request(path, token).then(setData).catch((e) => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(() => {
    let active = true
    request(path, token).then((value) => { if (active) setData(value) }).catch((e) => { if (active) setError(e.message) }).finally(() => { if (active) setLoading(false) })
    return () => { active = false }
  }, [path, token, refreshKey])
  return { data, error, loading, reload }
}
function State({ loading, error, empty }: { loading?: boolean; error?: string; empty?: boolean }) { if (loading) return <div className="state">Carregando dados da demonstração…</div>; if (error) return <div className="notice danger">Não foi possível carregar: {error}</div>; if (empty) return <div className="state">Ainda não há registros aqui.</div>; return null }

function Login({ onLogin }: { onLogin: (token: string) => void }) {
  const [email, setEmail] = useState('jovem@demo.local'); const [password, setPassword] = useState('Demo123!'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const r = await signIn(email, password); localStorage.setItem('terapia_token', r.access_token); onLogin(r.access_token) } catch (x) { setError((x as Error).message) } finally { setBusy(false) } }
  return <main className="login"><div className="loginCard"><div className="brand">Terap<span>IA</span><small>piloto simulado • apoio complementar</small></div><div className="notice"><b>IA de apoio, não terapeuta.</b> Esta demonstração usa somente dados sintéticos e pessoas fictícias.</div><form onSubmit={submit}><label>E-mail<input aria-label="E-mail" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>Senha<input aria-label="Senha" type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label>{error && <p className="error">{error}</p>}<button className="btn full" disabled={busy}>{busy ? 'Entrando…' : 'Entrar na demonstração'}</button></form><p className="mini">Persona sugerida: jovem@demo.local • senha Demo123!</p></div></main>
}
function Onboarding({ token, onDone }: { token: string; onDone: () => void }) {
  const [checked, setChecked] = useState(false); const [error, setError] = useState('')
  async function accept() { try { await request('/consents', token, { method: 'POST', body: JSON.stringify({ version: 'privacy-v3-demo-1', accepted: true }) }); onDone() } catch (e) { setError((e as Error).message) } }
  return <main className="login"><div className="loginCard wide"><span className="eyebrow">CONSENTIMENTO VERSIONADO</span><h1>Antes de começar</h1><div className="grid g2"><article className="card"><h3>O que é</h3><p>Uma ferramenta com IA para informação geral, autocuidado e caminhos de apoio humano.</p></article><article className="card"><h3>Limites</h3><p>Não é psicólogo, não diagnostica, não prescreve e não substitui atendimento profissional.</p></article><article className="card"><h3>Privacidade</h3><p>Seu diário fica fora do chat, dashboard e pesquisa. Dados opcionais podem ser exportados e excluídos.</p></article><article className="card"><h3>Quando buscar ajuda</h3><p>Em situação crítica, procure uma pessoa de confiança e serviços validados para sua região.</p></article></div><label className="consent"><input type="checkbox" checked={checked} onChange={(e) => setChecked(e.target.checked)} /> Li e aceito o consentimento privacy-v3-demo-1.</label>{error && <p className="error">{error}</p>}<button className="btn" disabled={!checked} onClick={accept}>Aceitar e continuar</button></div></main>
}
function Home({ token, go }: { token: string; go: (p: Page) => void }) { return <Home3 token={token} go={go} /> }
function Checkin({ token }: { token: string }) {
  const [period, setPeriod] = useState('all'); const [weekStart] = useState(() => new Date(Date.now() - 6 * 86400000).toISOString().slice(0, 10)); const path = period === '7' ? `/mood-checkins?from_date=${weekStart}` : '/mood-checkins'; const { data, error, loading, reload } = useLoad(path, token, period); const [context, setContext] = useState('Prefiro não informar'); const [message, setMessage] = useState('')
  async function save(mood: number) { await request('/mood-checkins', token, { method: 'POST', body: JSON.stringify({ mood, context }) }); setMessage('Check-in registrado. Se quiser, escolha uma prática curta de autocuidado.'); reload() }
  async function remove(id: number) { if (confirm('Excluir este check-in do seu histórico?')) { await request(`/mood-checkins/${id}`, token, { method: 'DELETE' }); reload() } }
  const average = data?.length ? (data.reduce((sum: number, x: any) => sum + x.mood, 0) / data.length).toFixed(1) : '—'
  return <div className="grid g2"><div className="card checkinCard"><span className="eyebrow">ESCALA 1–5 • AGORA</span><h3>Como você está neste momento?</h3><p className="muted">Não existe resposta certa e este registro não gera diagnóstico ou risco individual.</p><div className="moods">{[['😞', 'Muito difícil'], ['😕', 'Difícil'], ['😐', 'Neutro'], ['🙂', 'Bem'], ['😄', 'Muito bem']].map((x, i) => <button aria-label={`Humor ${i + 1}`} title={x[1]} key={x[1]} onClick={() => save(i + 1)}><span>{x[0]}</span><small>{x[1]}</small></button>)}</div><label>Contexto opcional<select value={context} onChange={(e) => setContext(e.target.value)}>{['Prefiro não informar', 'Estudos', 'Sono', 'Família', 'Amizades', 'Rotina'].map((x) => <option key={x}>{x}</option>)}</select></label>{message && <><div className="notice safe">✓ {message}</div><div className="nextSuggestions"><b>Próximos passos possíveis</b><span>♡ atividade breve</span><span>✓ organizar uma tarefa</span><span>◌ conversar com IA</span><span>⚑ procurar apoio humano</span></div></>}</div><div className="card"><div className="sectionHead"><div><h3>Seu histórico</h3><p className="muted">Média no período: <b>{average}/5</b></p></div><select aria-label="Período" value={period} onChange={(e) => setPeriod(e.target.value)}><option value="all">Todo período</option><option value="7">Últimos 7 dias</option></select></div><State loading={loading} error={error} empty={!data?.length} />{data?.length > 0 && <div className="trend" aria-label="Tendência de humor">{[...data].reverse().map((x: any) => <div key={x.id} title={`${x.mood}/5`} style={{ height: `${x.mood * 17}%` }} />)}</div>}{data?.map((x: any) => <div className="historyRow" key={x.id}><span className="moodDot">{x.mood}</span><div><b>{new Date(x.created_at).toLocaleString('pt-BR')}</b><small>{x.context}</small></div><button className="iconbtn" aria-label="Excluir check-in" onClick={() => remove(x.id)}>×</button></div>)}<div className="notice quiet">O dashboard recebe apenas contagens agregadas, nunca o contexto individual.</div></div></div>
}
function Journal({ token }: { token: string }) { return <Journal3 token={token} /> }
function Care({ token }: { token: string }) { return <Care3 token={token} /> }
const prompts = ['Estou ansioso por causa de uma prova.', 'Estou com dificuldade para dormir.', 'Como posso organizar minha rotina?', 'Quero conversar com alguém.', 'Acho que tenho depressão', 'Que dose de remédio devo tomar?', 'Você é a única pessoa que me entende', 'Não quero mais viver', 'Qual a previsão do tempo?']
function Chat({ token }: { token: string }) {
  const [text, setText] = useState(''); const [messages, setMessages] = useState<any[]>([{ role: 'bot', text: 'Olá. Sou uma IA de apoio educativo. Não faço diagnóstico nem prescrição.', response_type: 'disclosure', provider: 'policy', created_at: new Date().toISOString() }]); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState<Record<number, boolean>>({})
  async function sendText(q: string) { if (!q.trim() || busy) return; setText(''); setMessages((m) => [...m, { role: 'user', text: q, created_at: new Date().toISOString() }]); setBusy(true); try { const r = await request('/chat/messages', token, { method: 'POST', body: JSON.stringify({ text: q }) }); setMessages((m) => [...m, { role: 'bot', ...r }]) } catch (e) { setMessages((m) => [...m, { role: 'bot', text: `Não foi possível responder: ${(e as Error).message}`, response_type: 'provider_unavailable', created_at: new Date().toISOString() }]) } finally { setBusy(false) } }
  async function rate(id: number, useful: boolean) { await request(`/chat/messages/${id}/feedback`, token, { method: 'POST', body: JSON.stringify({ useful }) }); setFeedback((x) => ({ ...x, [id]: useful })) }
  return <div className="grid chatLayout"><div className="card chat immersiveChat"><div className="chatDisclosure">◌ <b>IA com limites + RAG</b><span>Fontes publicadas, safety anterior ao modelo e fallback explícito.</span></div><div className="msgs">{messages.map((m, i) => <div className={`msg ${m.role} type-${m.response_type}`} key={i}><div className="messageMeta"><b>{m.role === 'user' ? 'Você' : 'TerapIA • IA'}</b><time>{new Date(m.created_at || Date.now()).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}</time></div><p>{m.text}</p>{m.role === 'bot' && <div className="badges"><span className={`badge ${m.response_type}`}>{m.response_type}</span>{m.provider && <span className="badge">provider: {m.provider}</span>}{m.policy_events?.includes('GROUNDED_RESPONSE') && <span className="badge grounded">RAG ativo</span>}</div>}{m.source_refs?.map((s: any) => <div className="sourceCard" key={s.id}><span className="sourceIcon">⌘</span><b>Fonte validada: {s.title}</b><span>{s.source || s.kind}</span><small>v{s.version || 'política'} {s.category ? `• ${s.category}` : ''} {s.score ? `• relevância ${Math.round(s.score * 100)}%` : ''}</small></div>)}{m.message_id && <div className="messageFeedback"><span>Esta resposta foi útil?</span><button className={feedback[m.message_id] === true ? 'chosen' : ''} onClick={() => rate(m.message_id, true)}>Sim</button><button className={feedback[m.message_id] === false ? 'chosen' : ''} onClick={() => rate(m.message_id, false)}>Não</button></div>}</div>)}{busy && <div className="msg bot typing"><i/><i/><i/><span>Consultando fontes e proteções…</span></div>}</div><div className="quickPrompts">{prompts.slice(0, 4).map((p) => <button key={p} onClick={() => sendText(p)}>{p}</button>)}</div><form className="chatbox" onSubmit={(e) => { e.preventDefault(); sendText(text) }}><input aria-label="Mensagem" value={text} onChange={(e) => setText(e.target.value)} placeholder="Escreva sobre emoções, rotina ou autocuidado" /><button className="btn" disabled={busy}>Enviar</button></form></div><div><AIStatusCard token={token} compact /><div className="card promptPanel"><h3>Cenários de proteção</h3>{prompts.slice(4).map((p) => <button key={p} onClick={() => sendText(p)}>{p}</button>)}<div className="notice quiet"><b>Pipeline:</b> PII → safety → dependência → escopo → RAG → provider → saída → fonte.</div></div></div></div>
}
function Help({ token }: { token: string }) { const { data, error, loading } = useLoad('/help-contacts', token); return <><div className="notice danger"><b>Se houver perigo imediato, não espere pela IA.</b> Procure uma pessoa de confiança que possa ficar com você e um serviço de urgência validado para sua região.</div><div className="grid g3"><div className="card priority"><span>1</span><h3>Agora</h3><p>Afaste-se do que pode causar dano e fique perto de uma pessoa segura.</p></div><div className="card priority"><span>2</span><h3>Rede humana</h3><p>Avise alguém de confiança, familiar, equipe escolar preparada ou profissional.</p></div><div className="card priority"><span>3</span><h3>Serviço local</h3><p>Use apenas contatos verificados para sua localidade.</p></div></div><h2>Contatos da demonstração</h2><State loading={loading} error={error} /><div className="grid g2">{data?.map((x: any) => <div className="card contact" key={x.id}><span className="tag">DEMO • NÃO É CONTATO REAL</span><h3>{x.label}</h3><b>{x.value}</b><small>{x.region}</small></div>)}</div></> }
function Agenda({ token }: { token: string }) { return <Agenda3 token={token} /> }
function Privacy({ token }: { token: string }) {
  const consents = useLoad('/consents', token); const [status, setStatus] = useState('')
  async function download() { const data = await request('/privacy/export', token); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); a.download = 'terapia-meus-dados.json'; a.click(); URL.revokeObjectURL(a.href); setStatus('Exportação preparada localmente.') }
  async function remove() { if (confirm('Excluir diário, check-ins e conteúdo armazenado do chat?')) { const r = await request('/privacy/delete-request', token, { method: 'POST' }); setStatus(`Exclusão concluída: ${Object.values(r.deleted).reduce((a: any, b: any) => a + b, 0)} registros opcionais.`) } }
  async function notif(enabled: boolean) { await request('/privacy/notifications', token, { method: 'PUT', body: JSON.stringify({ enabled, discreet: true }) }); setStatus(enabled ? 'Notificações discretas ativadas.' : 'Notificações desativadas.') }
  async function revoke() { await request('/consents', token, { method: 'POST', body: JSON.stringify({ version: 'privacy-v3-demo-1', accepted: false }) }); setStatus('Revogação registrada no histórico.'); consents.reload() }
  return <><div className="grid g3 privacyMap"><div className="card"><span>Você controla</span><h3>Diário e check-ins</h3><p>Visualizar, editar, exportar e excluir.</p></div><div className="card"><span>Uso limitado</span><h3>Chat</h3><p>Texto bruto fora de analytics e pesquisa.</p></div><div className="card"><span>Separado</span><h3>Research Lab</h3><p>Somente dataset sintético isolado.</p></div></div><div className="grid g2"><div className="card"><h3>Ações de privacidade</h3><button className="btn2" onClick={download}>↓ Exportar meus dados</button><button className="dangerbtn" onClick={remove}>Excluir dados opcionais</button><button className="dangerbtn" onClick={revoke}>Revogar consentimento</button><hr /><h3>Notificações</h3><p className="muted">Sem conteúdo sensível na tela bloqueada.</p><button className="btn2" onClick={() => notif(true)}>Ativar discretas</button><button className="btn2" onClick={() => notif(false)}>Desativar</button>{status && <div className="notice safe">✓ {status}</div>}</div><div className="card"><h3>Histórico de consentimento</h3><State loading={consents.loading} error={consents.error} empty={!consents.data?.length} />{consents.data?.map((x: any) => <div className="historyRow" key={x.id}><span className={`consentMark ${x.accepted ? 'yes' : 'no'}`}>{x.accepted ? '✓' : '×'}</span><div><b>{x.version}</b><small>{x.accepted ? 'Aceito' : 'Revogado'} em {new Date(x.accepted_at).toLocaleString('pt-BR')}</small></div></div>)}</div></div></>
}
function Dashboard({ token }: { token: string }) {
  const { data, error, loading } = useLoad('/admin/dashboard', token); const names: Record<string, string> = { demo_accounts: 'Contas DEMO', checkins: 'Check-ins', selfcare_resources: 'Recursos', selfcare_completions: 'Práticas concluídas', appointments: 'Agendamentos', fallback_events: 'Fora de escopo', safety_events: 'Eventos safety', published_kb: 'KB publicada' }
  return <><div className="notice">DADOS SINTÉTICOS • Indicadores operacionais do banco. Sem diário, conversa bruta ou perfil individual.</div><State loading={loading} error={error} /><div className="kpis">{data && Object.entries(data.database).map(([k, v]) => <div className="card" key={k}><span>{String(v)}</span><b>{names[k] || k}</b></div>)}</div>{data && <div className="grid g2"><div className="card"><h3>Agendamentos por status</h3>{Object.entries(data.appointments_by_status).length ? Object.entries(data.appointments_by_status).map(([k, v]) => <div className="barRow" key={k}><span>{k}</span><div><i style={{ width: `${Math.min(100, Number(v) * 20)}%` }} /></div><b>{String(v)}</b></div>) : <div className="state">Nenhum agendamento.</div>}</div><div className="card"><h3>Privacidade de coortes</h3><p className="muted">Grupos com n &lt; {data.suppression_threshold} têm valor suprimido.</p>{data.cohorts.map((x: any) => <div className="historyRow" key={x.label}><span className="moodDot">{x.suppressed ? '—' : x.value}</span><div><b>{x.label}</b><small>{x.suppressed ? `suprimido (n < ${data.suppression_threshold})` : 'grupo exibido'}</small></div></div>)}</div></div>}</>
}
function Research({ token }: { token: string }) {
  const { data, error, loading } = useLoad('/research/model-card', token)
  return <><div className="notice danger"><b>NON-CLINICAL • DADOS SINTÉTICOS.</b> Não usar para diagnóstico, risco clínico ou decisão de cuidado.</div><State loading={loading} error={error} />{data && <><div className="grid g3">{data.models.map((m: any) => <div className="card model" key={m.name}><span className="tag">MODELO</span><h3>{m.name.replaceAll('_', ' ')}</h3><div><span><b>{Math.round(m.accuracy * 100)}%</b> accuracy</span><span><b>{m.roc_auc.toFixed(3)}</b> ROC-AUC</span></div></div>)}</div><div className="grid g2"><div className="card"><h3>Importância das variáveis</h3>{data.feature_importance.map((x: any) => <div className="barRow" key={x.feature}><span>{x.feature}</span><div><i style={{ width: `${x.importance * 100}%` }} /></div><b>{Math.round(x.importance * 100)}%</b></div>)}</div><div className="card"><h3>Model card</h3><p><b>Alvo:</b> {data.target}</p><p><b>Avaliação:</b> {data.evaluation}</p><p><b>Integração com chat:</b> {data.chat_integration ? 'sim' : 'não — isolamento obrigatório'}</p><p><b>Limitações:</b> {data.limitations}</p><div className="prohibited">{data.prohibited_uses.map((x: string) => <span key={x}>proibido: {x}</span>)}</div></div></div></>}</>
}
function Admin({ token }: { token: string }) {
  const knowledge = useLoad('/admin/knowledge', token); const policies = useLoad('/admin/policies', token); const [tab, setTab] = useState<'kb' | 'policies'>('kb'); const [message, setMessage] = useState(''); async function change(path: string, id: number, status: string) { try { await request(`${path}/${id}/status`, token, { method: 'PUT', body: JSON.stringify({ status }) }); setMessage(`Versão alterada para ${status}.`); knowledge.reload(); policies.reload() } catch (e) { setMessage((e as Error).message) } }; const list = tab === 'kb' ? knowledge : policies
  return <><AIStatusCard token={token} /><div className="notice">Publicação exige revisão identificada. O chatbot consulta exclusivamente versões <b>published</b>.</div><div className="tabs"><button className={tab === 'kb' ? 'active' : ''} onClick={() => setTab('kb')}>Knowledge base</button><button className={tab === 'policies' ? 'active' : ''} onClick={() => setTab('policies')}>Políticas</button></div>{message && <div className="notice safe">{message}</div>}<div className="card tableWrap"><State loading={list.loading} error={list.error} empty={!list.data?.length} /><table><thead><tr><th>Documento</th><th>Versão</th><th>Fonte / revisão</th><th>Status</th><th>Ação</th></tr></thead><tbody>{list.data?.map((x: any) => <tr key={x.id}><td><b>{x.title || x.code}</b><small>{x.slug || `policy-${x.code}`}</small></td><td>v{x.version}</td><td>{x.source || 'política interna'}<small>{x.reviewed_by || 'revisão pendente'}</small></td><td><span className={`status ${x.status}`}>{x.status}</span></td><td>{x.status === 'published' ? <button className="linkbtn" onClick={() => change(tab === 'kb' ? '/admin/knowledge' : '/admin/policies', x.id, 'archived')}>Despublicar</button> : <button className="linkbtn" disabled={!x.reviewed_by} onClick={() => change(tab === 'kb' ? '/admin/knowledge' : '/admin/policies', x.id, 'published')}>Publicar</button>}</td></tr>)}</tbody></table></div></>
}
export default function App() {
  const [token, setToken] = useState(localStorage.getItem('terapia_token') || ''); const [user, setUser] = useState<User | null>(null); const [ready, setReady] = useState(false); const [page, setPage] = useState<Page>('home')
  useEffect(() => { if (token) Promise.all([request('/me', token), request('/consents', token)]).then(([u, c]) => { setUser(u); setReady(c.some((x: any) => x.accepted)) }).catch(() => { localStorage.removeItem('terapia_token'); setToken('') }) }, [token])
  const allowed = useMemo(() => (p: Page) => user?.role === 'admin' ? ['home', 'dashboard', 'admin', 'research'].includes(p) : user?.role === 'researcher_aggregated' ? ['home', 'dashboard', 'research'].includes(p) : user?.role === 'young_user' ? !['dashboard', 'research', 'admin'].includes(p) : ['home', 'agenda'].includes(p), [user])
  if (!token) return <Login onLogin={setToken} />; if (!user) return <main className="login"><div className="state">Preparando ambiente seguro…</div></main>; if (!ready) return <Onboarding token={token} onDone={() => setReady(true)} />
  const content: Record<Page, React.ReactNode> = { home: <Home token={token} go={setPage} />, checkin: <Checkin token={token} />, journal: <Journal token={token} />, care: <Care token={token} />, chat: <Chat token={token} />, help: <Help token={token} />, agenda: <Agenda token={token} />, privacy: <Privacy token={token} />, dashboard: <Dashboard token={token} />, research: <Research token={token} />, admin: <Admin token={token} /> }
  return <><div className="topwarn">PILOTO SIMULADO • DADOS 100% SINTÉTICOS • IA DE APOIO, NÃO ATENDIMENTO PSICOLÓGICO</div><div id="app"><aside className="sidebar"><div className="brand">Terap<span>IA</span><small>IA local + UX • sprint 3</small></div><nav>{(Object.keys(labels) as Page[]).filter(allowed).map((p) => <button aria-label={labels[p][1]} className={page === p ? 'active' : ''} onClick={() => setPage(p)} key={p}>{labels[p][0]} <span>{labels[p][1]}</span></button>)}</nav><div className="who"><div className="avatar">{user.name.slice(0, 2).toUpperCase()}</div><div><b>{user.name}</b><small>{user.role} • sintético</small></div></div></aside><main><header><div><span className="eyebrow">TERAPIA / IA LOCAL + UX IMERSIVA</span><h1>{labels[page][1]}</h1><p>{labels[page][2]}</p></div><button className="btn2" onClick={() => { localStorage.removeItem('terapia_token'); setToken('') }}>Sair</button></header><section>{content[page]}</section></main></div></>
}
